module.exports = {
    prefix: '',
    important: false,
    separator: ':',
    theme: {
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
        },
        colors: {
            transparent: 'transparent',

            black: '#000',
            white: '#fff',
        },
        spacing: {
            px: '1px',
            '0': '0',
            '4': '1rem',
            '8': '2rem',
            '16': '4rem',
        },
        backgroundColor: theme => theme('colors'),
        backgroundPosition: {},
        backgroundSize: {},
        borderColor: {},
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            md: '0.375rem',
            lg: '0.5rem',
        },
        borderWidth: {},
        boxShadow: {
            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            none: 'none',
        },
        container: {},
        cursor: {
            pointer: 'pointer',
        },
        fill: {
            current: 'currentColor',
        },
        flex: {},
        flexGrow: {},
        flexShrink: {},
        fontFamily: {},
        fontSize: {
            sm: '0.875rem',
            lg: '1.125rem',
            xl: '1.25rem',
        },
        fontWeight: {},
        height: {},
        inset: {},
        letterSpacing: {},
        lineHeight: {},
        listStyleType: {},
        margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
        }),
        maxHeight: {},
        maxWidth: {},
        minHeight: {},
        minWidth: {},
        objectPosition: {},
        opacity: {},
        order: {},
        padding: theme => theme('spacing'),
        placeholderColor: theme => theme('colors'),
        stroke: {},
        strokeWidth: {},
        textColor: theme => theme('colors'),
        width: {},
        zIndex: {},
        gap: theme => theme('spacing'),
        gridTemplateColumns: {},
        gridColumn: {},
        gridColumnStart: {},
        gridColumnEnd: {},
        gridTemplateRows: {},
        gridRow: {},
        gridRowStart: {},
        gridRowEnd: {},
        transformOrigin: {},
        scale: {},
        rotate: {},
        translate: {},
        skew: {},
        transitionProperty: {},
        transitionTimingFunction: {},
        transitionDuration: {},
    },
    variants: {
        accessibility: ['responsive', 'focus'],
        alignContent: [],
        alignItems: [],
        alignSelf: [],
        appearance: [],
        backgroundAttachment: [],
        backgroundColor: [],
        backgroundPosition: [],
        backgroundRepeat: [],
        backgroundSize: [],
        borderCollapse: [],
        borderColor: [],
        borderRadius: [],
        borderStyle: [],
        borderWidth: [],
        boxShadow: ['responsive', 'hover', 'focus'],
        boxSizing: [],
        cursor: [],
        display: [],
        fill: [],
        flex: [],
        flexDirection: [],
        flexGrow: [],
        flexShrink: [],
        flexWrap: [],
        float: [],
        clear: [],
        fontFamily: [],
        fontSize: [],
        fontSmoothing: [],
        fontStyle: [],
        fontWeight: [],
        height: [],
        inset: [],
        justifyContent: [],
        letterSpacing: [],
        lineHeight: [],
        listStylePosition: [],
        listStyleType: [],
        margin: [],
        maxHeight: [],
        maxWidth: [],
        minHeight: [],
        minWidth: [],
        objectFit: [],
        objectPosition: [],
        opacity: [],
        order: [],
        outline: [],
        overflow: [],
        padding: [],
        placeholderColor: [],
        pointerEvents: [],
        position: [],
        resize: [],
        stroke: [],
        strokeWidth: [],
        tableLayout: [],
        textAlign: [],
        textColor: [],
        textDecoration: [],
        textTransform: [],
        userSelect: [],
        verticalAlign: [],
        visibility: [],
        whitespace: [],
        width: [],
        wordBreak: [],
        zIndex: [],
        gap: ['responsive'],
        gridAutoFlow: [],
        gridTemplateColumns: [],
        gridColumn: [],
        gridColumnStart: [],
        gridColumnEnd: [],
        gridTemplateRows: [],
        gridRow: [],
        gridRowStart: [],
        gridRowEnd: [],
        transform: [],
        transformOrigin: [],
        scale: [],
        rotate: [],
        translate: [],
        skew: [],
        transitionProperty: [],
        transitionTimingFunction: [],
        transitionDuration: [],
    },
    corePlugins: {},
    plugins: [],
};
