export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const UPDATE_CURRENT_URL = 'UPDATE_CURRENT_URL';
export const TOGGLE_AUTH_STATE = 'TOGGLE_AUTH_STATE';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
